import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as argon2 from 'argon2';
import { SecurityConfig } from '@hms/config';

@Injectable()
export class PasswordService {
  private readonly logger = new Logger(PasswordService.name);
  private readonly securityConfig: SecurityConfig;

  constructor(private readonly configService: ConfigService) {
    const config = this.configService.get<SecurityConfig>('security');
    if (!config) {
      throw new Error('[PasswordService] Security configuration is missing from ConfigService.');
    }
    this.securityConfig = config;
  }

  /**
   * Hashes a plaintext password using Argon2id with parameters from SecurityConfig.
   *
   * Requirements:
   * - Never logs, returns, or persists the plaintext password
   * - Uses cryptographically secure salt generated by Argon2
   * - Uses m=65536 KiB, t=3 iterations, p=4 parallelism threads from T01 config
   *
   * @param password Plaintext candidate password
   * @returns Argon2id encoded string (e.g. $argon2id$v=19$m=65536,p=4,t=3$...)
   */
  async hash(password: string): Promise<string> {
    if (!password || typeof password !== 'string') {
      throw new Error('Password must be a non-empty string.');
    }

    const { memoryCostKiB, timeCostIterations, parallelismThreads } =
      this.securityConfig.passwordPolicy;

    return argon2.hash(password, {
      type: argon2.argon2id,
      memoryCost: memoryCostKiB,
      timeCost: timeCostIterations,
      parallelism: parallelismThreads,
    });
  }

  /**
   * Verifies a candidate password against an Argon2id hash.
   *
   * Requirements:
   * - Constant-time / timing-safe verification provided by Argon2
   * - Invalid/malformed hashes handled safely (returns false, does not throw)
   * - Never exposes stored hash in logs or errors
   * - Never exposes user existence
   *
   * @param password Plaintext candidate password
   * @param hash Stored Argon2 hash
   * @returns boolean true if match, false otherwise
   */
  async verify(password: string, hash: string): Promise<boolean> {
    if (
      !password ||
      !hash ||
      typeof password !== 'string' ||
      typeof hash !== 'string' ||
      !hash.startsWith('$argon2')
    ) {
      return false;
    }

    try {
      return await argon2.verify(hash, password);
    } catch {
      // Catch malformed hash, invalid base64, salt errors safely
      return false;
    }
  }
}
