-- Migration for Procurement & Inventory models
-- Generated by implementation plan.

CREATE TABLE "suppliers" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "property_id" UUID NOT NULL,
  "name" VARCHAR(120) NOT NULL,
  "code" VARCHAR(30) NOT NULL,
  "contact" VARCHAR(100),
  "email" VARCHAR(100),
  "phone" VARCHAR(30),
  "active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "deleted_at" TIMESTAMPTZ(6),
  CONSTRAINT "suppliers_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_supplier_property_code" UNIQUE ("property_id", "code"),
  CONSTRAINT "fk_suppliers_property" FOREIGN KEY ("property_id") REFERENCES "properties" ("id") ON DELETE RESTRICT
);

CREATE INDEX "idx_supplier_property_active" ON "suppliers" ("property_id", "active");

CREATE TABLE "inventory_items" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "property_id" UUID NOT NULL,
  "name" VARCHAR(120) NOT NULL,
  "sku" VARCHAR(30) NOT NULL,
  "category" VARCHAR(60) NOT NULL,
  "unit" VARCHAR(20) NOT NULL,
  "reorder_level" INT NOT NULL DEFAULT 0,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "deleted_at" TIMESTAMPTZ(6),
  CONSTRAINT "inventory_items_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_inventory_item_property_sku" UNIQUE ("property_id", "sku"),
  CONSTRAINT "fk_inventory_items_property" FOREIGN KEY ("property_id") REFERENCES "properties" ("id") ON DELETE RESTRICT
);

CREATE INDEX "idx_inventory_item_property_category" ON "inventory_items" ("property_id", "category");

CREATE TYPE "PurchaseOrderStatus" AS ENUM ('DRAFT','SUBMITTED','APPROVED','PARTIALLY_RECEIVED','RECEIVED','CANCELLED');

CREATE TABLE "purchase_orders" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "property_id" UUID NOT NULL,
  "supplier_id" UUID NOT NULL,
  "po_number" VARCHAR(30) NOT NULL,
  "status" "PurchaseOrderStatus" NOT NULL DEFAULT 'DRAFT',
  "order_date" DATE NOT NULL,
  "expected_date" DATE,
  "total_amount" DECIMAL(12,4) NOT NULL DEFAULT 0,
  "notes" TEXT,
  "version" INT NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "deleted_at" TIMESTAMPTZ(6),
  CONSTRAINT "purchase_orders_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_purchase_order_property_number" UNIQUE ("property_id", "po_number"),
  CONSTRAINT "fk_po_property" FOREIGN KEY ("property_id") REFERENCES "properties" ("id") ON DELETE RESTRICT,
  CONSTRAINT "fk_po_supplier" FOREIGN KEY ("property_id", "supplier_id") REFERENCES "suppliers" ("property_id", "id") ON DELETE RESTRICT
);

CREATE INDEX "idx_purchase_order_property_status" ON "purchase_orders" ("property_id", "status");

CREATE TABLE "purchase_order_items" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "purchase_order_id" UUID NOT NULL,
  "inventory_item_id" UUID NOT NULL,
  "quantity" INT NOT NULL,
  "unit_cost" DECIMAL(12,4) NOT NULL,
  "total_cost" DECIMAL(12,4) NOT NULL,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "deleted_at" TIMESTAMPTZ(6),
  CONSTRAINT "purchase_order_items_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_po_item_po_item" UNIQUE ("purchase_order_id", "inventory_item_id"),
  CONSTRAINT "fk_po_item_po" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_po_item_inventory" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id") ON DELETE RESTRICT
);

CREATE TABLE "goods_receipts" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "property_id" UUID NOT NULL,
  "purchase_order_id" UUID NOT NULL,
  "receipt_number" VARCHAR(30) NOT NULL,
  "received_date" DATE NOT NULL,
  "status" VARCHAR(20) NOT NULL DEFAULT 'POSTED',
  "notes" TEXT,
  "idempotency_key" VARCHAR(64) NOT NULL,
  "version" INT NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "deleted_at" TIMESTAMPTZ(6),
  CONSTRAINT "goods_receipts_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_goods_receipt_property_number" UNIQUE ("property_id", "receipt_number"),
  CONSTRAINT "uq_goods_receipt_idempotency" UNIQUE ("idempotency_key"),
  CONSTRAINT "fk_goods_receipt_property" FOREIGN KEY ("property_id") REFERENCES "properties" ("id") ON DELETE RESTRICT,
  CONSTRAINT "fk_goods_receipt_po" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders" ("id") ON DELETE RESTRICT
);

CREATE TABLE "goods_receipt_items" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "receipt_id" UUID NOT NULL,
  "inventory_item_id" UUID NOT NULL,
  "ordered_quantity" INT NOT NULL,
  "received_quantity" INT NOT NULL,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "deleted_at" TIMESTAMPTZ(6),
  CONSTRAINT "goods_receipt_items_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_goods_receipt_item_receipt_item" UNIQUE ("receipt_id", "inventory_item_id"),
  CONSTRAINT "fk_goods_receipt_item_receipt" FOREIGN KEY ("receipt_id") REFERENCES "goods_receipts" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_goods_receipt_item_inventory" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id") ON DELETE RESTRICT
);

CREATE TABLE "stock_balances" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "property_id" UUID NOT NULL,
  "inventory_item_id" UUID NOT NULL,
  "on_hand" INT NOT NULL DEFAULT 0,
  "reserved" INT NOT NULL DEFAULT 0,
  "available" INT NOT NULL DEFAULT 0,
  "reorder_level" INT NOT NULL DEFAULT 0,
  "version" INT NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "deleted_at" TIMESTAMPTZ(6),
  CONSTRAINT "stock_balances_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_stock_balance_property_item" UNIQUE ("property_id", "inventory_item_id"),
  CONSTRAINT "fk_stock_balance_property" FOREIGN KEY ("property_id") REFERENCES "properties" ("id") ON DELETE RESTRICT,
  CONSTRAINT "fk_stock_balance_inventory" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id") ON DELETE RESTRICT
);

CREATE INDEX "idx_stock_balance_property_item" ON "stock_balances" ("property_id", "inventory_item_id");

-- End of migration

